
//! Autogenerated weights for `pallet_education_regions`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2025-12-02, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `recrafter-Legion-5-16IRX9`, CPU: `Intel(R) Core(TM) i7-14650HX`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/xcavate-node
// benchmark
// pallet
// --pallet
// pallet_education_regions
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ./pallets/education-regions/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

pub trait WeightInfo {
	fn propose_new_region() -> Weight;
	fn vote_on_region_proposal() -> Weight;
	fn unlock_region_voting_token() -> Weight;
	fn bid_on_region() -> Weight;
	fn create_new_region() -> Weight;
	fn propose_remove_regional_operator() -> Weight;
	fn vote_on_remove_owner_proposal() -> Weight;
	fn unlock_region_owner_removal_voting_token() -> Weight;
	fn bid_on_region_replacement() -> Weight;
	fn initiate_region_owner_resignation() -> Weight;
}

/// Weight functions for `pallet_regions`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionProposalId` (r:1 w:1)
	/// Proof: `EducationRegions::RegionProposalId` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionDetails` (r:1 w:0)
	/// Proof: `EducationRegions::RegionDetails` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::ProposalCounter` (r:1 w:1)
	/// Proof: `EducationRegions::ProposalCounter` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(373), added: 2848, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionProposals` (r:0 w:1)
	/// Proof: `EducationRegions::RegionProposals` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::LastRegionProposalBlock` (r:0 w:1)
	/// Proof: `EducationRegions::LastRegionProposalBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::OngoingRegionProposalVotes` (r:0 w:1)
	/// Proof: `EducationRegions::OngoingRegionProposalVotes` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	fn propose_new_region() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `378`
		//  Estimated: `3838`
		// Minimum execution time: 104_567_000 picoseconds.
		Weight::from_parts(107_799_000, 0)
			.saturating_add(Weight::from_parts(0, 3838))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `EducationRegions::RegionProposalId` (r:1 w:0)
	/// Proof: `EducationRegions::RegionProposalId` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionProposals` (r:1 w:0)
	/// Proof: `EducationRegions::RegionProposals` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(373), added: 2848, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::OngoingRegionProposalVotes` (r:1 w:1)
	/// Proof: `EducationRegions::OngoingRegionProposalVotes` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::UserRegionVote` (r:1 w:1)
	/// Proof: `EducationRegions::UserRegionVote` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	fn vote_on_region_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `624`
		//  Estimated: `3838`
		// Minimum execution time: 147_465_000 picoseconds.
		Weight::from_parts(149_807_000, 0)
			.saturating_add(Weight::from_parts(0, 3838))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `EducationRegions::UserRegionVote` (r:1 w:1)
	/// Proof: `EducationRegions::UserRegionVote` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionProposals` (r:1 w:0)
	/// Proof: `EducationRegions::RegionProposals` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(373), added: 2848, mode: `MaxEncodedLen`)
	fn unlock_region_voting_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `492`
		//  Estimated: `3838`
		// Minimum execution time: 84_294_000 picoseconds.
		Weight::from_parts(86_432_000, 0)
			.saturating_add(Weight::from_parts(0, 3838))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionProposalId` (r:1 w:0)
	/// Proof: `EducationRegions::RegionProposalId` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionProposals` (r:1 w:0)
	/// Proof: `EducationRegions::RegionProposals` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionAuctions` (r:1 w:1)
	/// Proof: `EducationRegions::RegionAuctions` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:2 w:2)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(373), added: 2848, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn bid_on_region() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3989`
		//  Estimated: `6686`
		// Minimum execution time: 183_297_000 picoseconds.
		Weight::from_parts(219_932_000, 0)
			.saturating_add(Weight::from_parts(0, 6686))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionAuctions` (r:1 w:1)
	/// Proof: `EducationRegions::RegionAuctions` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionProposalId` (r:0 w:1)
	/// Proof: `EducationRegions::RegionProposalId` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionDetails` (r:0 w:1)
	/// Proof: `EducationRegions::RegionDetails` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	fn create_new_region() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `442`
		//  Estimated: `3536`
		// Minimum execution time: 42_248_000 picoseconds.
		Weight::from_parts(44_101_000, 0)
			.saturating_add(Weight::from_parts(0, 3536))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `EducationRegions::RegionDetails` (r:1 w:0)
	/// Proof: `EducationRegions::RegionDetails` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionOwnerProposalId` (r:1 w:1)
	/// Proof: `EducationRegions::RegionOwnerProposalId` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(373), added: 2848, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::ProposalCounter` (r:1 w:1)
	/// Proof: `EducationRegions::ProposalCounter` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionOwnerRoundsExpiring` (r:1 w:1)
	/// Proof: `EducationRegions::RegionOwnerRoundsExpiring` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionOwnerProposals` (r:0 w:1)
	/// Proof: `EducationRegions::RegionOwnerProposals` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::OngoingRegionOwnerProposalVotes` (r:0 w:1)
	/// Proof: `EducationRegions::OngoingRegionOwnerProposalVotes` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	fn propose_remove_regional_operator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `566`
		//  Estimated: `3838`
		// Minimum execution time: 107_815_000 picoseconds.
		Weight::from_parts(110_355_000, 0)
			.saturating_add(Weight::from_parts(0, 3838))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `EducationRegions::RegionOwnerProposalId` (r:1 w:0)
	/// Proof: `EducationRegions::RegionOwnerProposalId` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(373), added: 2848, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::OngoingRegionOwnerProposalVotes` (r:1 w:1)
	/// Proof: `EducationRegions::OngoingRegionOwnerProposalVotes` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::UserRegionOwnerVote` (r:1 w:1)
	/// Proof: `EducationRegions::UserRegionOwnerVote` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	fn vote_on_remove_owner_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `675`
		//  Estimated: `3838`
		// Minimum execution time: 145_039_000 picoseconds.
		Weight::from_parts(149_335_000, 0)
			.saturating_add(Weight::from_parts(0, 3838))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `EducationRegions::UserRegionOwnerVote` (r:1 w:1)
	/// Proof: `EducationRegions::UserRegionOwnerVote` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionOwnerProposals` (r:1 w:0)
	/// Proof: `EducationRegions::RegionOwnerProposals` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(373), added: 2848, mode: `MaxEncodedLen`)
	fn unlock_region_owner_removal_voting_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `597`
		//  Estimated: `3838`
		// Minimum execution time: 85_334_000 picoseconds.
		Weight::from_parts(87_351_000, 0)
			.saturating_add(Weight::from_parts(0, 3838))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionDetails` (r:1 w:0)
	/// Proof: `EducationRegions::RegionDetails` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionReplacementAuctions` (r:1 w:1)
	/// Proof: `EducationRegions::RegionReplacementAuctions` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:2 w:2)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(373), added: 2848, mode: `MaxEncodedLen`)
	fn bid_on_region_replacement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `923`
		//  Estimated: `6686`
		// Minimum execution time: 158_312_000 picoseconds.
		Weight::from_parts(161_251_000, 0)
			.saturating_add(Weight::from_parts(0, 6686))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionDetails` (r:1 w:1)
	/// Proof: `EducationRegions::RegionDetails` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	fn initiate_region_owner_resignation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `409`
		//  Estimated: `3536`
		// Minimum execution time: 35_691_000 picoseconds.
		Weight::from_parts(37_688_000, 0)
			.saturating_add(Weight::from_parts(0, 3536))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
