//! Autogenerated weights for pallet_bucket
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 33.0.0
//! DATE: 2025-04-09
//! STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rust-2`, CPU: `12th Gen Intel(R) Core(TM) i9-12900K`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_imports)]
#![allow(clippy::as_conversions)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_bucket.
pub trait WeightInfo {
	fn create_namespace() -> Weight;
	fn add_manager() -> Weight;
	fn force_add_manager() -> Weight;
	fn force_remove_namespace() -> Weight;
	fn remove_manager() -> Weight;
	fn create_bucket() -> Weight;
	fn force_remove_bucket() -> Weight;
	fn add_admin() -> Weight;
	fn remove_admin() -> Weight;
	fn add_contributor() -> Weight;
	fn remove_contributor() -> Weight;
	fn resume_writing() -> Weight;
	fn pause_writing() -> Weight;
	fn rotate_key() -> Weight;
	fn create_tag() -> Weight;
	fn write() -> Weight;
	fn force_remove_message() -> Weight;
}

/// Weights for pallet_bucket using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `PalletBucket::Namespaces` (r:1 w:1)
	/// Proof: `PalletBucket::Namespaces` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `PalletBucket::Managers` (r:0 w:1)
	/// Proof: `PalletBucket::Managers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_namespace() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `3681`
		// Minimum execution time: 410_387 nanoseconds.
		Weight::from_parts(419_487_000, 3681)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `PalletBucket::Namespaces` (r:1 w:0)
	/// Proof: `PalletBucket::Namespaces` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Managers` (r:1 w:1)
	/// Proof: `PalletBucket::Managers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_manager() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `268`
		//  Estimated: `3733`
		// Minimum execution time: 211_621 nanoseconds.
		Weight::from_parts(213_089_000, 3733)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Namespaces` (r:1 w:0)
	/// Proof: `PalletBucket::Namespaces` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Managers` (r:0 w:1)
	/// Proof: `PalletBucket::Managers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_add_manager() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `200`
		//  Estimated: `3665`
		// Minimum execution time: 161_713 nanoseconds.
		Weight::from_parts(168_032_000, 3665)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Buckets` (r:1 w:0)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Namespaces` (r:1 w:1)
	/// Proof: `PalletBucket::Namespaces` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_remove_namespace() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `166`
		//  Estimated: `3631`
		// Minimum execution time: 187_641 nanoseconds.
		Weight::from_parts(195_226_000, 3631)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Namespaces` (r:1 w:0)
	/// Proof: `PalletBucket::Namespaces` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Managers` (r:1 w:1)
	/// Proof: `PalletBucket::Managers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_manager() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `268`
		//  Estimated: `3733`
		// Minimum execution time: 213_373 nanoseconds.
		Weight::from_parts(221_220_000, 3733)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Namespaces` (r:1 w:0)
	/// Proof: `PalletBucket::Namespaces` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Managers` (r:1 w:0)
	/// Proof: `PalletBucket::Managers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::NextBucketId` (r:1 w:1)
	/// Proof: `PalletBucket::NextBucketId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `PalletBucket::Buckets` (r:0 w:1)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_bucket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `411`
		//  Estimated: `3876`
		// Minimum execution time: 477_257 nanoseconds.
		Weight::from_parts(480_427_000, 3876)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `PalletBucket::Messages` (r:1 w:0)
	/// Proof: `PalletBucket::Messages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Buckets` (r:1 w:1)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_remove_bucket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `320`
		//  Estimated: `3785`
		// Minimum execution time: 201_595 nanoseconds.
		Weight::from_parts(203_138_000, 3785)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Buckets` (r:1 w:0)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Managers` (r:1 w:0)
	/// Proof: `PalletBucket::Managers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Admins` (r:0 w:1)
	/// Proof: `PalletBucket::Admins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_admin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `385`
		//  Estimated: `3850`
		// Minimum execution time: 222_021 nanoseconds.
		Weight::from_parts(224_111_000, 3850)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Buckets` (r:1 w:0)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Managers` (r:1 w:0)
	/// Proof: `PalletBucket::Managers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Admins` (r:0 w:1)
	/// Proof: `PalletBucket::Admins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_admin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `418`
		//  Estimated: `3883`
		// Minimum execution time: 223_199 nanoseconds.
		Weight::from_parts(224_507_000, 3883)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Buckets` (r:1 w:0)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Managers` (r:1 w:0)
	/// Proof: `PalletBucket::Managers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Contributors` (r:0 w:1)
	/// Proof: `PalletBucket::Contributors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_contributor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `418`
		//  Estimated: `3883`
		// Minimum execution time: 222_678 nanoseconds.
		Weight::from_parts(223_794_000, 3883)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Buckets` (r:1 w:0)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Managers` (r:1 w:0)
	/// Proof: `PalletBucket::Managers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Contributors` (r:0 w:1)
	/// Proof: `PalletBucket::Contributors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_contributor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `418`
		//  Estimated: `3883`
		// Minimum execution time: 223_903 nanoseconds.
		Weight::from_parts(226_098_000, 3883)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Admins` (r:1 w:0)
	/// Proof: `PalletBucket::Admins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Buckets` (r:1 w:1)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn resume_writing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `418`
		//  Estimated: `3883`
		// Minimum execution time: 200_578 nanoseconds.
		Weight::from_parts(201_521_000, 3883)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Admins` (r:1 w:0)
	/// Proof: `PalletBucket::Admins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Buckets` (r:1 w:1)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn pause_writing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `436`
		//  Estimated: `3901`
		// Minimum execution time: 197_198 nanoseconds.
		Weight::from_parts(198_816_000, 3901)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Admins` (r:1 w:0)
	/// Proof: `PalletBucket::Admins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Buckets` (r:1 w:1)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn rotate_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `436`
		//  Estimated: `3901`
		// Minimum execution time: 197_447 nanoseconds.
		Weight::from_parts(198_713_000, 3901)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Admins` (r:1 w:0)
	/// Proof: `PalletBucket::Admins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `PalletBucket::Tags` (r:0 w:1)
	/// Proof: `PalletBucket::Tags` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_tag() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `455`
		//  Estimated: `3920`
		// Minimum execution time: 432_283 nanoseconds.
		Weight::from_parts(434_790_000, 3920)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `PalletBucket::Buckets` (r:1 w:1)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Contributors` (r:1 w:0)
	/// Proof: `PalletBucket::Contributors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Tags` (r:1 w:0)
	/// Proof: `PalletBucket::Tags` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `PalletBucket::Messages` (r:0 w:1)
	/// Proof: `PalletBucket::Messages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn write() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `856`
		//  Estimated: `4321`
		// Minimum execution time: 565_473 nanoseconds.
		Weight::from_parts(569_738_000, 4321)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `PalletBucket::Messages` (r:1 w:1)
	/// Proof: `PalletBucket::Messages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_remove_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `781`
		//  Estimated: `4246`
		// Minimum execution time: 148_505 nanoseconds.
		Weight::from_parts(149_729_000, 4246)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `PalletBucket::Namespaces` (r:1 w:1)
	/// Proof: `PalletBucket::Namespaces` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `PalletBucket::Managers` (r:0 w:1)
	/// Proof: `PalletBucket::Managers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_namespace() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `3681`
		// Minimum execution time: 410_387 nanoseconds.
		Weight::from_parts(419_487_000, 3681)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `PalletBucket::Namespaces` (r:1 w:0)
	/// Proof: `PalletBucket::Namespaces` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Managers` (r:1 w:1)
	/// Proof: `PalletBucket::Managers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_manager() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `268`
		//  Estimated: `3733`
		// Minimum execution time: 211_621 nanoseconds.
		Weight::from_parts(213_089_000, 3733)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Namespaces` (r:1 w:0)
	/// Proof: `PalletBucket::Namespaces` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Managers` (r:0 w:1)
	/// Proof: `PalletBucket::Managers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_add_manager() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `200`
		//  Estimated: `3665`
		// Minimum execution time: 161_713 nanoseconds.
		Weight::from_parts(168_032_000, 3665)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Buckets` (r:1 w:0)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Namespaces` (r:1 w:1)
	/// Proof: `PalletBucket::Namespaces` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_remove_namespace() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `166`
		//  Estimated: `3631`
		// Minimum execution time: 187_641 nanoseconds.
		Weight::from_parts(195_226_000, 3631)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Namespaces` (r:1 w:0)
	/// Proof: `PalletBucket::Namespaces` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Managers` (r:1 w:1)
	/// Proof: `PalletBucket::Managers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_manager() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `268`
		//  Estimated: `3733`
		// Minimum execution time: 213_373 nanoseconds.
		Weight::from_parts(221_220_000, 3733)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Namespaces` (r:1 w:0)
	/// Proof: `PalletBucket::Namespaces` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Managers` (r:1 w:0)
	/// Proof: `PalletBucket::Managers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::NextBucketId` (r:1 w:1)
	/// Proof: `PalletBucket::NextBucketId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `PalletBucket::Buckets` (r:0 w:1)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_bucket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `411`
		//  Estimated: `3876`
		// Minimum execution time: 477_257 nanoseconds.
		Weight::from_parts(480_427_000, 3876)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `PalletBucket::Messages` (r:1 w:0)
	/// Proof: `PalletBucket::Messages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Buckets` (r:1 w:1)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_remove_bucket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `320`
		//  Estimated: `3785`
		// Minimum execution time: 201_595 nanoseconds.
		Weight::from_parts(203_138_000, 3785)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Buckets` (r:1 w:0)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Managers` (r:1 w:0)
	/// Proof: `PalletBucket::Managers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Admins` (r:0 w:1)
	/// Proof: `PalletBucket::Admins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_admin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `385`
		//  Estimated: `3850`
		// Minimum execution time: 222_021 nanoseconds.
		Weight::from_parts(224_111_000, 3850)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Buckets` (r:1 w:0)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Managers` (r:1 w:0)
	/// Proof: `PalletBucket::Managers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Admins` (r:0 w:1)
	/// Proof: `PalletBucket::Admins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_admin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `418`
		//  Estimated: `3883`
		// Minimum execution time: 223_199 nanoseconds.
		Weight::from_parts(224_507_000, 3883)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Buckets` (r:1 w:0)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Managers` (r:1 w:0)
	/// Proof: `PalletBucket::Managers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Contributors` (r:0 w:1)
	/// Proof: `PalletBucket::Contributors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_contributor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `418`
		//  Estimated: `3883`
		// Minimum execution time: 222_678 nanoseconds.
		Weight::from_parts(223_794_000, 3883)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Buckets` (r:1 w:0)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Managers` (r:1 w:0)
	/// Proof: `PalletBucket::Managers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Contributors` (r:0 w:1)
	/// Proof: `PalletBucket::Contributors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_contributor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `418`
		//  Estimated: `3883`
		// Minimum execution time: 223_903 nanoseconds.
		Weight::from_parts(226_098_000, 3883)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Admins` (r:1 w:0)
	/// Proof: `PalletBucket::Admins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Buckets` (r:1 w:1)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn resume_writing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `418`
		//  Estimated: `3883`
		// Minimum execution time: 200_578 nanoseconds.
		Weight::from_parts(201_521_000, 3883)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Admins` (r:1 w:0)
	/// Proof: `PalletBucket::Admins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Buckets` (r:1 w:1)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn pause_writing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `436`
		//  Estimated: `3901`
		// Minimum execution time: 197_198 nanoseconds.
		Weight::from_parts(198_816_000, 3901)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Admins` (r:1 w:0)
	/// Proof: `PalletBucket::Admins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Buckets` (r:1 w:1)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn rotate_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `436`
		//  Estimated: `3901`
		// Minimum execution time: 197_447 nanoseconds.
		Weight::from_parts(198_713_000, 3901)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `PalletBucket::Admins` (r:1 w:0)
	/// Proof: `PalletBucket::Admins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `PalletBucket::Tags` (r:0 w:1)
	/// Proof: `PalletBucket::Tags` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_tag() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `455`
		//  Estimated: `3920`
		// Minimum execution time: 432_283 nanoseconds.
		Weight::from_parts(434_790_000, 3920)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `PalletBucket::Buckets` (r:1 w:1)
	/// Proof: `PalletBucket::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Contributors` (r:1 w:0)
	/// Proof: `PalletBucket::Contributors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PalletBucket::Tags` (r:1 w:0)
	/// Proof: `PalletBucket::Tags` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `PalletBucket::Messages` (r:0 w:1)
	/// Proof: `PalletBucket::Messages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn write() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `856`
		//  Estimated: `4321`
		// Minimum execution time: 565_473 nanoseconds.
		Weight::from_parts(569_738_000, 4321)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `PalletBucket::Messages` (r:1 w:1)
	/// Proof: `PalletBucket::Messages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_remove_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `781`
		//  Estimated: `4246`
		// Minimum execution time: 148_505 nanoseconds.
		Weight::from_parts(149_729_000, 4246)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
