
//! Autogenerated weights for `pallet_bucket`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2025-10-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `recrafter-Legion-5-16IRX9`, CPU: `Intel(R) Core(TM) i7-14650HX`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/xcavate-node
// benchmark
// pallet
// --pallet
// pallet_bucket
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ./pallets/pallet-bucket/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions needed for pallet_bucket.
pub trait WeightInfo {
	fn create_namespace() -> Weight;
	fn add_manager() -> Weight;
	fn force_add_manager() -> Weight;
	fn force_remove_namespace() -> Weight;
	fn remove_manager() -> Weight;
	fn create_bucket() -> Weight;
	fn force_remove_bucket() -> Weight;
	fn force_remove_tag() -> Weight;
	fn add_admin() -> Weight;
	fn remove_admin() -> Weight;
	fn add_contributor() -> Weight;
	fn remove_contributor() -> Weight;
	fn resume_writing() -> Weight;
	fn pause_writing() -> Weight;
	fn rotate_key() -> Weight;
	fn create_tag() -> Weight;
	fn write() -> Weight;
	fn force_remove_message() -> Weight;
}

/// Weights for pallet_bucket using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Buckets::NextNamespaceId` (r:1 w:1)
	/// Proof: `Buckets::NextNamespaceId` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Namespaces` (r:1 w:1)
	/// Proof: `Buckets::Namespaces` (`max_values`: None, `max_size`: Some(2928), added: 5403, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Managers` (r:0 w:1)
	/// Proof: `Buckets::Managers` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn create_namespace() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `144`
		//  Estimated: `6393`
		// Minimum execution time: 80_919_000 picoseconds.
		Weight::from_parts(83_790_000, 0)
			.saturating_add(Weight::from_parts(0, 6393))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Buckets::Namespaces` (r:1 w:0)
	/// Proof: `Buckets::Namespaces` (`max_values`: None, `max_size`: Some(2928), added: 5403, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Managers` (r:1 w:1)
	/// Proof: `Buckets::Managers` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn add_manager() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `229`
		//  Estimated: `6393`
		// Minimum execution time: 25_182_000 picoseconds.
		Weight::from_parts(25_958_000, 0)
			.saturating_add(Weight::from_parts(0, 6393))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Buckets::Namespaces` (r:1 w:0)
	/// Proof: `Buckets::Namespaces` (`max_values`: None, `max_size`: Some(2928), added: 5403, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Managers` (r:0 w:1)
	/// Proof: `Buckets::Managers` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn force_add_manager() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `160`
		//  Estimated: `6393`
		// Minimum execution time: 18_204_000 picoseconds.
		Weight::from_parts(19_324_000, 0)
			.saturating_add(Weight::from_parts(0, 6393))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Buckets::Buckets` (r:1 w:0)
	/// Proof: `Buckets::Buckets` (`max_values`: None, `max_size`: Some(2801), added: 5276, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Managers` (r:1 w:0)
	/// Proof: `Buckets::Managers` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Namespaces` (r:1 w:1)
	/// Proof: `Buckets::Namespaces` (`max_values`: None, `max_size`: Some(2928), added: 5403, mode: `MaxEncodedLen`)
	fn force_remove_namespace() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2994`
		//  Estimated: `6393`
		// Minimum execution time: 35_350_000 picoseconds.
		Weight::from_parts(36_927_000, 0)
			.saturating_add(Weight::from_parts(0, 6393))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Buckets::Namespaces` (r:1 w:0)
	/// Proof: `Buckets::Namespaces` (`max_values`: None, `max_size`: Some(2928), added: 5403, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Managers` (r:3 w:1)
	/// Proof: `Buckets::Managers` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn remove_manager() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `287`
		//  Estimated: `8655`
		// Minimum execution time: 42_290_000 picoseconds.
		Weight::from_parts(44_451_000, 0)
			.saturating_add(Weight::from_parts(0, 8655))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Buckets::Namespaces` (r:1 w:0)
	/// Proof: `Buckets::Namespaces` (`max_values`: None, `max_size`: Some(2928), added: 5403, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Managers` (r:1 w:0)
	/// Proof: `Buckets::Managers` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::NextBucketId` (r:1 w:1)
	/// Proof: `Buckets::NextBucketId` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Buckets` (r:0 w:1)
	/// Proof: `Buckets::Buckets` (`max_values`: None, `max_size`: Some(2801), added: 5276, mode: `MaxEncodedLen`)
	fn create_bucket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `405`
		//  Estimated: `6393`
		// Minimum execution time: 85_153_000 picoseconds.
		Weight::from_parts(87_757_000, 0)
			.saturating_add(Weight::from_parts(0, 6393))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Buckets::Messages` (r:1 w:0)
	/// Proof: `Buckets::Messages` (`max_values`: None, `max_size`: Some(3189), added: 5664, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Admins` (r:1 w:0)
	/// Proof: `Buckets::Admins` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Contributors` (r:1 w:0)
	/// Proof: `Buckets::Contributors` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Tags` (r:1 w:0)
	/// Proof: `Buckets::Tags` (`max_values`: None, `max_size`: Some(250), added: 2725, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Buckets` (r:1 w:1)
	/// Proof: `Buckets::Buckets` (`max_values`: None, `max_size`: Some(2801), added: 5276, mode: `MaxEncodedLen`)
	fn force_remove_bucket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2938`
		//  Estimated: `6654`
		// Minimum execution time: 50_148_000 picoseconds.
		Weight::from_parts(52_343_000, 0)
			.saturating_add(Weight::from_parts(0, 6654))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Buckets::TagMessages` (r:1 w:0)
	/// Proof: `Buckets::TagMessages` (`max_values`: None, `max_size`: Some(254), added: 2729, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Tags` (r:1 w:1)
	/// Proof: `Buckets::Tags` (`max_values`: None, `max_size`: Some(250), added: 2725, mode: `MaxEncodedLen`)
	fn force_remove_tag() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `484`
		//  Estimated: `3719`
		// Minimum execution time: 27_553_000 picoseconds.
		Weight::from_parts(28_997_000, 0)
			.saturating_add(Weight::from_parts(0, 3719))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Buckets::Buckets` (r:1 w:0)
	/// Proof: `Buckets::Buckets` (`max_values`: None, `max_size`: Some(2801), added: 5276, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Managers` (r:1 w:0)
	/// Proof: `Buckets::Managers` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Admins` (r:0 w:1)
	/// Proof: `Buckets::Admins` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn add_admin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `327`
		//  Estimated: `6266`
		// Minimum execution time: 27_152_000 picoseconds.
		Weight::from_parts(28_089_000, 0)
			.saturating_add(Weight::from_parts(0, 6266))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Buckets::Buckets` (r:1 w:0)
	/// Proof: `Buckets::Buckets` (`max_values`: None, `max_size`: Some(2801), added: 5276, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Managers` (r:1 w:0)
	/// Proof: `Buckets::Managers` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Admins` (r:0 w:1)
	/// Proof: `Buckets::Admins` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn remove_admin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `360`
		//  Estimated: `6266`
		// Minimum execution time: 27_073_000 picoseconds.
		Weight::from_parts(28_196_000, 0)
			.saturating_add(Weight::from_parts(0, 6266))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Buckets::Buckets` (r:1 w:0)
	/// Proof: `Buckets::Buckets` (`max_values`: None, `max_size`: Some(2801), added: 5276, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Admins` (r:1 w:0)
	/// Proof: `Buckets::Admins` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Contributors` (r:0 w:1)
	/// Proof: `Buckets::Contributors` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn add_contributor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `360`
		//  Estimated: `6266`
		// Minimum execution time: 27_418_000 picoseconds.
		Weight::from_parts(28_308_000, 0)
			.saturating_add(Weight::from_parts(0, 6266))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Buckets::Buckets` (r:1 w:0)
	/// Proof: `Buckets::Buckets` (`max_values`: None, `max_size`: Some(2801), added: 5276, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Admins` (r:1 w:0)
	/// Proof: `Buckets::Admins` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Contributors` (r:0 w:1)
	/// Proof: `Buckets::Contributors` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn remove_contributor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `397`
		//  Estimated: `6266`
		// Minimum execution time: 28_152_000 picoseconds.
		Weight::from_parts(30_715_000, 0)
			.saturating_add(Weight::from_parts(0, 6266))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Buckets::Admins` (r:1 w:0)
	/// Proof: `Buckets::Admins` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Buckets` (r:1 w:1)
	/// Proof: `Buckets::Buckets` (`max_values`: None, `max_size`: Some(2801), added: 5276, mode: `MaxEncodedLen`)
	fn resume_writing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3037`
		//  Estimated: `6266`
		// Minimum execution time: 37_334_000 picoseconds.
		Weight::from_parts(38_811_000, 0)
			.saturating_add(Weight::from_parts(0, 6266))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Buckets::Admins` (r:1 w:0)
	/// Proof: `Buckets::Admins` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Buckets` (r:1 w:1)
	/// Proof: `Buckets::Buckets` (`max_values`: None, `max_size`: Some(2801), added: 5276, mode: `MaxEncodedLen`)
	fn pause_writing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3069`
		//  Estimated: `6266`
		// Minimum execution time: 37_632_000 picoseconds.
		Weight::from_parts(39_416_000, 0)
			.saturating_add(Weight::from_parts(0, 6266))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Buckets::Admins` (r:1 w:0)
	/// Proof: `Buckets::Admins` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Buckets` (r:1 w:1)
	/// Proof: `Buckets::Buckets` (`max_values`: None, `max_size`: Some(2801), added: 5276, mode: `MaxEncodedLen`)
	fn rotate_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3069`
		//  Estimated: `6266`
		// Minimum execution time: 42_083_000 picoseconds.
		Weight::from_parts(48_814_000, 0)
			.saturating_add(Weight::from_parts(0, 6266))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Buckets::Admins` (r:1 w:0)
	/// Proof: `Buckets::Admins` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Tags` (r:0 w:1)
	/// Proof: `Buckets::Tags` (`max_values`: None, `max_size`: Some(250), added: 2725, mode: `MaxEncodedLen`)
	fn create_tag() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `416`
		//  Estimated: `3593`
		// Minimum execution time: 81_157_000 picoseconds.
		Weight::from_parts(102_585_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Buckets::Buckets` (r:1 w:1)
	/// Proof: `Buckets::Buckets` (`max_values`: None, `max_size`: Some(2801), added: 5276, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Contributors` (r:1 w:0)
	/// Proof: `Buckets::Contributors` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Tags` (r:1 w:0)
	/// Proof: `Buckets::Tags` (`max_values`: None, `max_size`: Some(250), added: 2725, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::TagMessages` (r:1 w:1)
	/// Proof: `Buckets::TagMessages` (`max_values`: None, `max_size`: Some(254), added: 2729, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::Messages` (r:0 w:1)
	/// Proof: `Buckets::Messages` (`max_values`: None, `max_size`: Some(3189), added: 5664, mode: `MaxEncodedLen`)
	fn write() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3522`
		//  Estimated: `6266`
		// Minimum execution time: 123_943_000 picoseconds.
		Weight::from_parts(130_268_000, 0)
			.saturating_add(Weight::from_parts(0, 6266))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Buckets::Messages` (r:1 w:1)
	/// Proof: `Buckets::Messages` (`max_values`: None, `max_size`: Some(3189), added: 5664, mode: `MaxEncodedLen`)
	/// Storage: `Buckets::TagMessages` (r:1 w:1)
	/// Proof: `Buckets::TagMessages` (`max_values`: None, `max_size`: Some(254), added: 2729, mode: `MaxEncodedLen`)
	fn force_remove_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3698`
		//  Estimated: `6654`
		// Minimum execution time: 41_901_000 picoseconds.
		Weight::from_parts(43_423_000, 0)
			.saturating_add(Weight::from_parts(0, 6654))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
