
//! Autogenerated weights for `pallet_real_x_education`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2025-12-15, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `recrafter-Legion-5-16IRX9`, CPU: `Intel(R) Core(TM) i7-14650HX`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/xcavate-node
// benchmark
// pallet
// --pallet
// pallet_real_x_education
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ./pallets/real-x-education/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

pub trait WeightInfo {
	fn create_module() -> Weight;
	fn sponsor_module() -> Weight;
	fn book_module() -> Weight;
	fn claim_booking() -> Weight;
	fn submit_impact_score() -> Weight;
	fn mint_recipient_nft() -> Weight;
	fn finish_booking_process() -> Weight;
	fn burn_unsponsored_token() -> Weight;
	fn remove_module() -> Weight;
	fn reclaim_unused_sponsorship() -> Weight;
	fn cancel_booking() -> Weight;
	fn clear_old_cancellations() -> Weight;
	fn cancel_claim() -> Weight;
	fn register_module_deliverer() -> Weight;
	fn unregister_module_deliverer() -> Weight;
}

/// Weight functions for `pallet_real_x_education`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionDetails` (r:1 w:0)
	/// Proof: `EducationRegions::RegionDetails` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::NextModuleId` (r:1 w:1)
	/// Proof: `RealXEducation::NextModuleId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(391), added: 2866, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::NextCollectionId` (r:1 w:1)
	/// Proof: `EducationNfts::NextCollectionId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::Collection` (r:1 w:1)
	/// Proof: `EducationNfts::Collection` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::NextNftId` (r:1 w:1)
	/// Proof: `RealXEducation::NextNftId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::Item` (r:1 w:1)
	/// Proof: `EducationNfts::Item` (`max_values`: None, `max_size`: Some(861), added: 3336, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::ItemConfigOf` (r:1 w:1)
	/// Proof: `EducationNfts::ItemConfigOf` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::ItemMetadataOf` (r:1 w:1)
	/// Proof: `EducationNfts::ItemMetadataOf` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::NextAssetId` (r:1 w:1)
	/// Proof: `RealXEducation::NextAssetId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Asset` (r:1 w:1)
	/// Proof: `EducationAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::NextAssetId` (r:1 w:0)
	/// Proof: `EducationAssets::NextAssetId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Account` (r:1 w:1)
	/// Proof: `EducationAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Metadata` (r:1 w:1)
	/// Proof: `EducationAssets::Metadata` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:0 w:1)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::CollectionRoleOf` (r:0 w:1)
	/// Proof: `EducationNfts::CollectionRoleOf` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::CollectionConfigOf` (r:0 w:1)
	/// Proof: `EducationNfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::Account` (r:0 w:1)
	/// Proof: `EducationNfts::Account` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::CollectionAccount` (r:0 w:1)
	/// Proof: `EducationNfts::CollectionAccount` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	fn create_module() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `863`
		//  Estimated: `6196`
		// Minimum execution time: 390_520_000 picoseconds.
		Weight::from_parts(398_901_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(17))
			.saturating_add(T::DbWeight::get().writes(19))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(103), added: 2578, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Asset` (r:1 w:1)
	/// Proof: `EducationAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Account` (r:2 w:2)
	/// Proof: `EducationAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::NextSponsorId` (r:1 w:1)
	/// Proof: `RealXEducation::NextSponsorId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::SponsoredModules` (r:0 w:1)
	/// Proof: `RealXEducation::SponsoredModules` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn sponsor_module() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2090`
		//  Estimated: `6208`
		// Minimum execution time: 211_249_000 picoseconds.
		Weight::from_parts(216_704_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(11))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::SponsoredModules` (r:1 w:1)
	/// Proof: `RealXEducation::SponsoredModules` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::NextBookingId` (r:1 w:1)
	/// Proof: `RealXEducation::NextBookingId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(391), added: 2866, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Asset` (r:1 w:1)
	/// Proof: `EducationAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Account` (r:2 w:2)
	/// Proof: `EducationAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::Bookings` (r:0 w:1)
	/// Proof: `RealXEducation::Bookings` (`max_values`: None, `max_size`: Some(238), added: 2713, mode: `MaxEncodedLen`)
	fn book_module() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1515`
		//  Estimated: `6208`
		// Minimum execution time: 204_771_000 picoseconds.
		Weight::from_parts(211_402_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::Bookings` (r:1 w:1)
	/// Proof: `RealXEducation::Bookings` (`max_values`: None, `max_size`: Some(238), added: 2713, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleDeliverer` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleDeliverer` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	fn claim_booking() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1098`
		//  Estimated: `3703`
		// Minimum execution time: 68_770_000 picoseconds.
		Weight::from_parts(70_474_000, 0)
			.saturating_add(Weight::from_parts(0, 3703))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::Bookings` (r:1 w:1)
	/// Proof: `RealXEducation::Bookings` (`max_values`: None, `max_size`: Some(238), added: 2713, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:0)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionDetails` (r:1 w:0)
	/// Proof: `EducationRegions::RegionDetails` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleDeliverer` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleDeliverer` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Asset` (r:1 w:1)
	/// Proof: `EducationAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Account` (r:1 w:1)
	/// Proof: `EducationAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:5 w:5)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:5 w:5)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(103), added: 2578, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::NextNftId` (r:1 w:1)
	/// Proof: `RealXEducation::NextNftId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::Item` (r:3 w:3)
	/// Proof: `EducationNfts::Item` (`max_values`: None, `max_size`: Some(861), added: 3336, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::Collection` (r:1 w:1)
	/// Proof: `EducationNfts::Collection` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::CollectionConfigOf` (r:1 w:0)
	/// Proof: `EducationNfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::ItemConfigOf` (r:3 w:3)
	/// Proof: `EducationNfts::ItemConfigOf` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::CollectionRoleOf` (r:1 w:0)
	/// Proof: `EducationNfts::CollectionRoleOf` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::ItemMetadataOf` (r:3 w:3)
	/// Proof: `EducationNfts::ItemMetadataOf` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::Account` (r:0 w:3)
	/// Proof: `EducationNfts::Account` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn submit_impact_score() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4237`
		//  Estimated: `14035`
		// Minimum execution time: 652_914_000 picoseconds.
		Weight::from_parts(665_862_000, 0)
			.saturating_add(Weight::from_parts(0, 14035))
			.saturating_add(T::DbWeight::get().reads(33))
			.saturating_add(T::DbWeight::get().writes(31))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::Bookings` (r:1 w:0)
	/// Proof: `RealXEducation::Bookings` (`max_values`: None, `max_size`: Some(238), added: 2713, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:0)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::NextNftId` (r:1 w:1)
	/// Proof: `RealXEducation::NextNftId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::Item` (r:1 w:1)
	/// Proof: `EducationNfts::Item` (`max_values`: None, `max_size`: Some(861), added: 3336, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::Collection` (r:1 w:1)
	/// Proof: `EducationNfts::Collection` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::CollectionConfigOf` (r:1 w:0)
	/// Proof: `EducationNfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::ItemConfigOf` (r:1 w:1)
	/// Proof: `EducationNfts::ItemConfigOf` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::CollectionRoleOf` (r:1 w:0)
	/// Proof: `EducationNfts::CollectionRoleOf` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::ItemMetadataOf` (r:1 w:1)
	/// Proof: `EducationNfts::ItemMetadataOf` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::Account` (r:0 w:1)
	/// Proof: `EducationNfts::Account` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn mint_recipient_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2062`
		//  Estimated: `4326`
		// Minimum execution time: 145_985_000 picoseconds.
		Weight::from_parts(151_544_000, 0)
			.saturating_add(Weight::from_parts(0, 4326))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::Bookings` (r:1 w:1)
	/// Proof: `RealXEducation::Bookings` (`max_values`: None, `max_size`: Some(238), added: 2713, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(391), added: 2866, mode: `MaxEncodedLen`)
	fn finish_booking_process() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1236`
		//  Estimated: `3856`
		// Minimum execution time: 104_118_000 picoseconds.
		Weight::from_parts(109_555_000, 0)
			.saturating_add(Weight::from_parts(0, 3856))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Account` (r:1 w:1)
	/// Proof: `EducationAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Asset` (r:1 w:1)
	/// Proof: `EducationAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	fn burn_unsponsored_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1073`
		//  Estimated: `3675`
		// Minimum execution time: 98_155_000 picoseconds.
		Weight::from_parts(100_331_000, 0)
			.saturating_add(Weight::from_parts(0, 3675))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Asset` (r:1 w:1)
	/// Proof: `EducationAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Metadata` (r:1 w:1)
	/// Proof: `EducationAssets::Metadata` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(391), added: 2866, mode: `MaxEncodedLen`)
	fn remove_module() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1301`
		//  Estimated: `6196`
		// Minimum execution time: 149_353_000 picoseconds.
		Weight::from_parts(152_281_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::SponsoredModules` (r:1 w:1)
	/// Proof: `RealXEducation::SponsoredModules` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(103), added: 2578, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Asset` (r:1 w:1)
	/// Proof: `EducationAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Account` (r:2 w:2)
	/// Proof: `EducationAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn reclaim_unused_sponsorship() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2526`
		//  Estimated: `6208`
		// Minimum execution time: 214_916_000 picoseconds.
		Weight::from_parts(222_372_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::Bookings` (r:1 w:1)
	/// Proof: `RealXEducation::Bookings` (`max_values`: None, `max_size`: Some(238), added: 2713, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::BookingCancellationCounter` (r:1 w:1)
	/// Proof: `RealXEducation::BookingCancellationCounter` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Asset` (r:1 w:1)
	/// Proof: `EducationAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Account` (r:2 w:2)
	/// Proof: `EducationAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(391), added: 2866, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::SponsoredModules` (r:1 w:1)
	/// Proof: `RealXEducation::SponsoredModules` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleDeliverer` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleDeliverer` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::SchoolCancellations` (r:0 w:1)
	/// Proof: `RealXEducation::SchoolCancellations` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn cancel_booking() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2109`
		//  Estimated: `6208`
		// Minimum execution time: 217_751_000 picoseconds.
		Weight::from_parts(223_637_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(11))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::SchoolCancellations` (r:51 w:50)
	/// Proof: `RealXEducation::SchoolCancellations` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::BookingCancellationCounter` (r:1 w:1)
	/// Proof: `RealXEducation::BookingCancellationCounter` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn clear_old_cancellations() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2653`
		//  Estimated: `131295`
		// Minimum execution time: 518_645_000 picoseconds.
		Weight::from_parts(532_740_000, 0)
			.saturating_add(Weight::from_parts(0, 131295))
			.saturating_add(T::DbWeight::get().reads(53))
			.saturating_add(T::DbWeight::get().writes(51))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::Bookings` (r:1 w:1)
	/// Proof: `RealXEducation::Bookings` (`max_values`: None, `max_size`: Some(238), added: 2713, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleDeliverer` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleDeliverer` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	fn cancel_claim() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1134`
		//  Estimated: `3703`
		// Minimum execution time: 68_257_000 picoseconds.
		Weight::from_parts(70_943_000, 0)
			.saturating_add(Weight::from_parts(0, 3703))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleDeliverer` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleDeliverer` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(391), added: 2866, mode: `MaxEncodedLen`)
	fn register_module_deliverer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `421`
		//  Estimated: `3856`
		// Minimum execution time: 93_396_000 picoseconds.
		Weight::from_parts(96_313_000, 0)
			.saturating_add(Weight::from_parts(0, 3856))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:1)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleDeliverer` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleDeliverer` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(391), added: 2866, mode: `MaxEncodedLen`)
	fn unregister_module_deliverer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `575`
		//  Estimated: `3856`
		// Minimum execution time: 94_365_000 picoseconds.
		Weight::from_parts(98_181_000, 0)
			.saturating_add(Weight::from_parts(0, 3856))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
}
